# -*- coding: utf-8 -*-



# Form implementation generated from reading ui file 'input.ui'

#

# Created by: PyQt5 UI code generator 5.15.1

#

# WARNING: Any manual changes made to this file will be lost when pyuic5 is

# run again.  Do not edit this file unless you know what you are doing.



import random

from PyQt5 import QtCore, QtGui, QtWidgets, QtSvg

from CharField import CharField, PasswordField
from QIconMaterial import QIconMaterial

        

class ComboBox(QtWidgets.QComboBox):

    focus_in_signal = QtCore.pyqtSignal()

    focus_out_signal = QtCore.pyqtSignal()



    def focusInEvent(self, event):

        self.focus_in_signal.emit()

        super().focusInEvent(event)



    def focusOutEvent(self, event):

        super().focusOutEvent(event)

        self.focus_out_signal.emit()



    popupAboutToBeShown = QtCore.pyqtSignal()

    def showPopup(self):

        super(ComboBox, self).showPopup()

        self.popupAboutToBeShown.emit()

        



class CustomStyleDelegate(QtWidgets.QStyledItemDelegate):

    def initStyleOption(self, option, index):

        super(CustomStyleDelegate, self).initStyleOption(option, index)

        random_color = QtGui.QColor("#eaeaea")

        option.backgroundBrush = random_color



    def paint(self, painter, option, index):

        super(CustomStyleDelegate, self).paint(painter, option, index)

        margins = 0

        





class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")

        MainWindow.resize(640, 480)

        font = QtGui.QFont()

        font.setPointSize(11)

        MainWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.centralwidget.setObjectName("centralwidget")



        

        username = CharField(name_field="Username", size_font=11, max_length=200, central=self.centralwidget, ud=80)

        # password = PasswordField(name_field="Password", size_font=11, max_length=200, central=self.centralwidget, ud=140)



        self.label = QtWidgets.QLabel(self.centralwidget)

        self.label.setGeometry(QtCore.QRect(68, 151 - 20, 201, 31))

        fontt = QtGui.QFont()

        fontt.setPointSize(11 - 3)

        self.label.setFont(fontt)

        self.label.setStyleSheet("color: #1E88E5;")

        self.label.setObjectName("label_name")

        self.label.setText("Select")



        self.comboBox = ComboBox(self.centralwidget)

        self.comboBox.setGeometry(QtCore.QRect(68, 151, 201, 31))

        self.comboBox.setAutoFillBackground(False)

        self.comboBox.setStyleSheet("""QComboBox{

            background: transparent;

            border: 0px;

            border-bottom:1px solid #1E88E5;

        }

        QComboBox:focus{

            border-bottom:2px solid #0D47A1;

        }

        

        QComboBox QAbstractItemView {

            background: #ffffff;

            selection-background-color: #e8e8e8;

            outline: none;

        }

        QComboBox::drop-down

        {

            border-width: 0px;

        }



        QWidget::item {

            color: #1E88E5;

            padding: 9px 11px;

        }

        QWidget::item:hover {

            background: #c5c5c5;

            color: #1E88E5;

            padding: 9px 11px;

        }

        QWidget::item:selected:active{

            background: #c5c5c5;

            color: #1E88E5;

            padding: 9px 11px;

        }



        QComboBox QAbstractScrollArea QScrollBar:vertical {

            border: none;

            background-color: #ffffff;

            margin: 0px 0 0px 0;

            width: 8px;

         }

        QComboBox QAbstractScrollArea QScrollBar::handle:vertical {

             background: black;

             min-height: 50px;

            border-radius: 4px;

         }

        QComboBox QAbstractScrollArea QScrollBar::up-arrow:vertical, QComboBox QAbstractScrollArea QScrollBar::down-arrow:vertical {

            border: none;

            background: none;

            color: none;

         }

        QComboBox QAbstractScrollArea QScrollBar::add-line:vertical {

            border: none;

            background: none;

            width: 0px;

            height: 0px;

        }



        QComboBox QAbstractScrollArea QScrollBar::sub-line:vertical {

            border: none;

            background: none;

            width: 0px;

            height: 0px;

        }

        """

        )

        self.comboBox.setEditable(False)

        self.comboBox.setMaxVisibleItems(4)

        self.comboBox.setObjectName("comboBox")

        self.comboBox.addItem("1")

        self.comboBox.addItem("2")

        self.comboBox.addItem("3")

        self.comboBox.addItem("4")

        self.comboBox.addItem("5")

        self.comboBox.addItem("6")

        self.comboBox.addItem("7")

        self.comboBox.addItem("8")

        self.comboBox.addItem("9")

        self.comboBox.addItem("10")

        delegate = CustomStyleDelegate(self.comboBox)

        self.comboBox.setItemDelegate(delegate)



        self.comboBox.currentIndexChanged.connect(lambda: self.selectionChange())

        self.comboBox.focus_in_signal.connect(lambda: self.focus_in())

        self.comboBox.focus_out_signal.connect(lambda: self.focus_out())

        self.comboBox.activated.connect(lambda: self.activatedSelection())

        

        self.button_pass = QtWidgets.QPushButton(self.centralwidget)

        self.button_pass.setGeometry(QtCore.QRect(240, 154, 24, 24))

        self.button_pass.setStyleSheet("QPushButton  {\n"

        "    border-radius: 12; border: 0; outline: 0;\n"

        "    background: transparent;\n"

        "    color: #ff00ff;\n"

        "}\n"

        "\n"

        "QPushButton:hover {\n"

        "    background: #c5c5c5;\n"

        "}")

        self.button_pass.setText("")



        self.icon_eye = QIconMaterial("expand_more-24px.svg").iconSVG()

        self.icon_no_eye = QIconMaterial("visibility_off-24px.svg").iconSVG()



        self.button_pass.setIcon(self.icon_eye)

        self.button_pass.setToolTip("Show Options")

        self.button_pass.setObjectName("sde")

        self.button_pass.clicked.connect(lambda: self.buttonPopup())





        MainWindow.setCentralWidget(self.centralwidget)



        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def buttonPopup(self):

        self.comboBox.showPopup()



    def focus_in(self):

        self.label.setStyleSheet("color: #0D47A1;")



    def focus_out(self):

        self.label.setStyleSheet("color: #1E88E5;")



    def activatedSelection(self):

        self.label.setStyleSheet("color: #0D47A1;")



    def selectionChange(self):

        self.comboBox.setFocus(True)





    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))





if __name__ == "__main__":

    import sys

    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()

    ui.setupUi(MainWindow)

    MainWindow.show()

    sys.exit(app.exec_())
